function alias_fish
alias s='sudo'
alias zypper='sudo zypper'
alias z='sudo zypper'
alias ls='eza --icons -1 -a'
alias la='eza -a --icons -1'
alias ll='eza -lah --icons'
alias rm='rm -i'
alias vi='lvim'
alias vim='lvim'
aliad nvim='lvim'
alias c='/home/rajnish/data/bash-script/clang-16.sh'
alias nano='lvim'
alias add-alias='lvim ~/.config/fish/functions/alias_fish.fish'
alias bashrc='lvim ~/.config/fish/config.fish'
alias code-c='cd ~/data/codes/c/'
alias cx='cd ~/data/codes/c/cx'
alias d='cd ~/data'
alias cl='clear; ls -a' 
end 
