#!/bin/bash

# Function to check if the current directory is a Git repository
check_git_repository() {
    if [ ! -d ".git" ]; then
        echo "This directory is not a git repository."
        exit 1
    fi
}

# Function to check for changes in the repository
check_for_changes() {
    if git status --porcelain | grep -q .; then
        echo "Changes detected. Automatically staging changes..."
        echo " [*] --> git status -sbv "
        git status -sbv
        return 0
    else
        echo "No changes detected in the repository. Nothing to add."
        exit 0
    fi
}

# Function to add and commit changes
add_and_commit_changes() {
    echo "
    [ # ] --> git add -i
    "
    git add -i

    echo "
    [ # ] --> git commit
    "
    git commit
}

# Function to push changes to the remote repository
push_changes() {

    echo "
    [*] --> git remote add   <src-name>:origin   <link>
    "

    local default_cmd="git push -u origin master"

    read -e -i "$default_cmd" user_input

    if [ -n "$user_input" ]; then

       echo "
       [ #e ] -->  $user_input
       "

       eval " $user_input "
    else
        echo "
        [ #d ] -->  $default_cmd
        "


         $default_cmd
    fi
}

# Main script execution
check_git_repository
check_for_changes
add_and_commit_changes
push_changes
